add test

diff --git a/.github/workflows/ros2_ci_cd.yml b/.github/workflows/ros2_ci_cd.yml
--- a/.github/workflows/ros2_ci_cd.yml
+++ b/.github/workflows/ros2_ci_cd.yml
@@ -52,14 +52,14 @@
           if: steps.build_test.outcome == 'failure'
           run: echo "result - failure" && exit 1
 
-        # - name: Run tests
-        #   id: run_test
-        #   run: |
-        #     . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
-        #     colcon test &&
-        #     colcon test-result
-        #   continue-on-error: true
+        - name: Run tests
+          id: run_test
+          run: |
+            . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+            colcon test &&
+            colcon test-result
+          continue-on-error: true
         
-        # - name: run_test command success
-        #   if: steps.run_test.outcome == 'failure'
-        #   run: echo "result -failed" && exit 1
+        - name: run_test command success
+          if: steps.run_test.outcome == 'failure'
+          run: echo "result -failed" && exit 1
