Update ros2_ci_cd.yml

diff --git a/.github/workflows/ros2_ci_cd.yml b/.github/workflows/ros2_ci_cd.yml
--- a/.github/workflows/ros2_ci_cd.yml
+++ b/.github/workflows/ros2_ci_cd.yml
@@ -1,65 +1,65 @@
-name: build and test
+  name: build and test
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+  on:
+    push:
+      branches: [ main ]
+    pull_request:
+      branches: [ main ]
 
-jobs:
-  build_and_test:
-    strategy:
-      matrix:
-        os: 
-          - ubuntu-22.04
-        rosdistro:
-          - humble
-      
-    runs-on: ${{ matrix.os }}
+  jobs:
+    build_and_test:
+      strategy:
+        matrix:
+          os: 
+            - ubuntu-22.04
+          rosdistro:
+            - humble
+        
+      runs-on: ${{ matrix.os }}
 
-    container:
-      image: ros:${{ matrix.rosdistro}}-ros-base
-    steps:
-      - name: Setup directories
-        run: mkdir -p ros2_ws/src
+      container:
+        image: ros:${{ matrix.rosdistro}}-ros-base
+      steps:
+        - name: Setup directories
+          run: mkdir -p ros2_ws/src
 
-      - name: Check out repository
-        uses: actions/checkout@v3
-        with: 
-          path: ros2_ws/src/simple_project
+        - name: Check out repository
+          uses: actions/checkout@v3
+          with: 
+            path: ros2_ws/src/simple_project
 
-      - name: Install dependencies
-        run: |
-          rosdep update &&
-          apt-get update &&
-          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro}}
+        - name: Install dependencies
+          run: |
+            rosdep update &&
+            apt-get update &&
+            rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro}}
 
-      - name: Install diagnostic-updater
-        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
-      
-      - name: Build test
-        id: build_test
-        run: |
-          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
-          colcon build
-        continue-on-error: true
-      
-      - name: build_test command success
-        if: steps.build_test.outcome == 'success'
-        run: echo "result - success"
+        - name: Install diagnostic-updater
+          run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
+        
+        - name: Build test
+          id: build_test
+          run: |
+            . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+            colcon build
+          continue-on-error: true
+        
+        - name: build_test command success
+          if: steps.build_test.outcome == 'success'
+          run: echo "result - success"
 
-      - name: build_test command failure
-        if: steps.build_test.outcome == 'failure'
-        run: echo "result - failure" && exit 1
+        - name: build_test command failure
+          if: steps.build_test.outcome == 'failure'
+          run: echo "result - failure" && exit 1
 
-      - name: Run tests
-        id: run_test
-        run: |
-          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
-          colcon test &&
-          colcon test-result
-        continue-on-error: true
-      
-      - name: run_test command success
-        if: steps.run_test.outcome == 'failure'
-        run: echo "result -failed" && exit 1
+        # - name: Run tests
+        #   id: run_test
+        #   run: |
+        #     . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+        #     colcon test &&
+        #     colcon test-result
+        #   continue-on-error: true
+        
+        # - name: run_test command success
+        #   if: steps.run_test.outcome == 'failure'
+        #   run: echo "result -failed" && exit 1
