Update ros2_ci_cd.yml

diff --git a/.github/workflows/ros2_ci_cd.yml b/.github/workflows/ros2_ci_cd.yml
--- a/.github/workflows/ros2_ci_cd.yml
+++ b/.github/workflows/ros2_ci_cd.yml
@@ -10,19 +10,57 @@ on:
 
 jobs:
   build_and_test:
-    runs-on: ubuntu-latest
-    container:
-      image: ros:humble-ros-base
-    steps:
-      - uses : actions/checkout@v2
-      - name : Environment Setup
-        run: |
-          sudo apt update && sudo apt install -y python3-colcon-common-extensions
-          source /opt/ros/humble/setup.bash
+    strategy:
+    matrix:
+      os: 
+        - ubuntu-22.04
+      rosdistro:
+        - humble
       
-      - name : Build package
-        run: colcon build --packages-select  simple_project --symlink-install
-      - name : Test package
-        run: colcon test --packages-select simple_project --symlink-install
-      - name : Test Result
-        run: colcon test-result --verbose
+    runs-on: ubuntu-latest
+
+    container:
+      image: ros:${{ matrix.rosdistro}}-ros-base
+    steps:
+      - name: Setup directories
+        run: mkdir -p ros2_ws/src
+
+      - name: Check out repository
+        uses: actions/checkout@v3
+        with: ros2_ws/src/ros2_topic_sample
+
+      - name: Install dependencies
+        run: |
+          rosdep update &&
+          apt-get update &&
+          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro}}
+
+      - name: Install diagnostic-updater
+        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
+      
+      - name: Build test
+        id: build_test
+        run: |
+          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+          colcon build
+        continue-on-error: true
+      
+      - name: build_test command success
+        if: steps.build_test.outcome == 'success'
+        run: echo "result - success"
+
+      - name: build_test command failure
+        if: steps.build_test.outcome == 'failure'
+        run: echo "result - failure" && exit 1
+
+      - name: Run tests
+        id: run_test
+        run: |
+          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+          colcon test &&
+          colcon test-result
+        continue-on-error: true
+      
+      - name: run_test command success
+        if: steps.run_test.outcome == 'failure'
+        run: echo "result -failed" && exit 1
